INFO:     Will watch for changes in these directories: ['/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [16679] using WatchFiles
INFO:     Started server process [16763]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:63898 - "GET /ping HTTP/1.1" 200 OK
INFO:     127.0.0.1:63901 - "GET /books/ HTTP/1.1" 401 Unauthorized
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
INFO:     127.0.0.1:63904 - "POST /auth/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:63909 - "GET /books/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:63912 - "POST /books/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/fastapi/routing.py", line 328, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/Users/gilos/Desktop/ComputerScience/Projects/trackerNow/backend/.venv/lib/python3.13/site-packages/fastapi/routing.py", line 177, in serialize_response
    raise ResponseValidationError(
        errors=_normalize_errors(errors), body=response_content
    )
fastapi.exceptions.ResponseValidationError: 1 validation errors:
  {'type': 'list_type', 'loc': ('response', 'tags'), 'msg': 'Input should be a valid list', 'input': '["programming", "clean code", "software engineering"]'}

WARNING:  WatchFiles detected changes in 'app/schemas/resource.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [16763]
INFO:     Started server process [19762]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'app/schemas/resource.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [19762]
INFO:     Started server process [19852]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:63925 - "POST /books/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:63928 - "POST /videos/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:63932 - "GET /books/stats/overview HTTP/1.1" 200 OK
INFO:     127.0.0.1:63935 - "GET /videos/stats/overview HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'migrate_create_books_videos.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [19852]
INFO:     Started server process [22768]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'migrate_add_user_id.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [22768]
INFO:     Started server process [22821]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'app/main.py', 'app/models/__init__.py', 'app/models/resource.py', 'app/models/application.py', 'app/routers/books.py', 'app/schemas/resource.py', 'app/services/videos.py', 'app/db/session.py', 'app/services/books.py', 'app/routers/videos.py', 'migrate_add_user_id.py', 'app/models/problem.py', 'app/models/user.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [22821]
INFO:     Started server process [23111]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'app/models/problem.py', 'app/schemas/resource.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [23111]
INFO:     Started server process [23164]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
